site_name: My Docs
nav:
  - Home: index.md
  - AWS: aws.md
  - Kubernetes: kubernetes.md
  - Terraform: terraform.md
  - Linux: linux.md
  - DevOps: devops.md
  - Docker: docker.md
  - Git: git.md
  - GitHub: github.md
  - GitHub Actions: githubactions.md
  - GitLab: gitlab.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
