site_name: RootEdu
nav:
  - Home: index.md
  - AWS: aws.md
  - Kubernetes: kubernetes.md
  - Terraform: terraform.md
  - Linux: linux.md
  - DevOps: devops.md
  - Docker: docker.md
  - Git: git.md
  - GitHub: github.md
  - GitHub Actions: githubactions.md
  - GitLab: gitlab.md

theme:
  name: gitbook

plugins: []

extra:
  nav:
    sort_order: reverse

repo_url: https://gitlab.com/lramage/mkdocs-gitbook-theme


